name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleRelease
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: demo.apk
          path: app/build/outputs/apk/debug/app-debug.apk
